### ISSUE TITLE
Abnormal behavior when using "/" for search

### ISSUE THREAD

**Issue by huyfam** [axelfahy/jupyterlab-vim#38]
I usually use "/" in vim command mode to search for a string, press enter to go to the first occurence, then press n/N to jump to the next one. The behavior didn't maintain in jupyterlab-vim. Instead, every occurence of the searched string were marked black and I  couldn't even get rid of these black marks. The behavior was totally broken. 
Am I missing something ? Please enlighten me.

**Comment by ianhi** [comment]
The search gets highlighted black which I think is also the default in "real" vim. You can remove the highlights again by typing `:noh`

As for search with n/N I've always found that it works for me, is it possible you can't see the cursor due to the black highlights? Also, I'd you can replicate the issue on https://codemirror.net/demo/vim.html then it's a problem with the code mirror vim implementation rather than this extension

**Comment by huyfam** [comment]
Thanks for the tip. Yes, you were right. It was due to the black highlights that I thought "/" didn't work. The codemirror worked great, with yellow highlights. Can we modify this highlighting color in jupyterlab?

**Comment by ianhi** [comment]
>  Can we modify this highlighting color in jupyterlab?

This color is decided by the theme you are using. I don't think this extension should get into the business of messing around with jlab-wide theming. There was some discussion of this on the juptyerlab repo that you may be interested in: https://github.com/jupyterlab/jupyterlab/issues/8207

**Comment by huyfam** [comment]
I got it. Thanks for your help.
